#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

key=$(ynh_string_random --length=64)
ynh_app_setting_set --key=key --value=$key

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing dependencies..."

ynh_nodejs_install

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template=".env" --destination="$install_dir/.env"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "$app" --description="Startpage for your server" --log="/var/log/$app/$app.log"

#=================================================
# INSTALL APP
#=================================================
ynh_script_progression "Installing the app..."

pushd "$install_dir"
 	ynh_hide_warnings ynh_exec_as_app npm run dev-init
popd

pushd "$install_dir/client"
 	ynh_hide_warnings ynh_exec_as_app npm run build
popd

mkdir -p "$install_dir/{data,public}"
mv $install_dir/client/build/* $install_dir/public
chmod -R o-rwx "$install_dir/"
chown -R $app: "$install_dir/"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
